---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-db-backup-pvc
  namespace: openshift-etcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: gp3-csi
